### ISSUE TITLE
HLSPlayer does not seem to work anymore

### ISSUE THREAD

**Issue by anomitra** [pBuddhi/hotstar#1]
The [website](https://www.hlsplayer.net/) to which the redirects were served has probably stopped working. Did not work for me. I used the copied M3U8 stream in another Chrome extension to play the stream.

**Comment by pBuddhi** [comment]
THEOplayer has been used in place of HLSplayer. The extension is working fine now.

**Comment by anomitra** [comment]
Cheers @pBuddhi, this works great. You might want to check out a [native HLS player](https://github.com/video-dev/hls.js), could eliminate the THEOplayer dependency. Thanks again!

**Comment by pBuddhi** [comment]
Thanks @anomitra for letting me know about the issue. I will definitely try the suggested library.

**Comment by pBuddhi** [comment]
@anomitra I removed THEOplayer dependency by using [hls.js](https://github.com/video-dev/hls.js) library. Check out the extension now.

**Comment by anomitra** [comment]
It works great now. Thank you! :smile:

**Comment by anomitra** [comment]
This seems to have broken down again :disappointed: I looked into the logs and it appears that the server on which they are hosting the M3U8 streams have stopped supporting cross-origin requests. So, possibly nothing we can do now. I did drop a frustrated email to their support team, but no expectations of a response.

**Comment by pBuddhi** [comment]
I looked it up and its working fine. Can you check it out?
